name = "ExtendableASGFEM"
uuid = "a4750d0b-645d-4217-869c-e25952806e24"
version = "1.0.0"
authors = ["Christian Merdon <merdon@wias-berlin.de>", "Martin Eigel <martin.eigel@wias-berlin.de>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ExtendableFEM = "a722555e-65e0-4074-a036-ca7ce79a4aed"
ExtendableFEMBase = "12fb9182-3d4c-4424-8fd1-727a0899810c"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Aqua = "0.8"
CairoMakie = "0.13.10"
DataFrames = "1.8.1"
Distributed = "1.9"
Distributions = "0.25.120"
DocStringExtensions = "0.9.4"
Documenter = "1.15.0"
DoubleFloats = "1.4.3"
DrWatson = "2.19.1"
ExplicitImports = "1"
ExtendableFEM = "1.3"
ExtendableFEMBase = "1.3"
ExtendableGrids = "1.13"
ExtendableSparse = "1.7"
GridVisualize = "1.12"
IterativeSolvers = "0.9.2"
Krylov = "0.10.1"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.9"
Printf = "1.9"
Random = "1.9"
SparseArrays = "1.9"
SpecialFunctions = "2.5.1"
StaticArrays = "1.9.13"
Test = "1.9"
UnicodePlots = "3.8.1"
julia = "^1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ExplicitImports", "DoubleFloats", "Test"]
